### ISSUE TITLE
Ticking memory connection when equipping Steadfast Spaulders in 

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/WitchingGadgets#26]
http://pastebin.com/Td7hvrEv

This error occurred when I tried to equip Steadfast Spaulders .Game crashed to desktop in version 1.1.3 of Witching Gadgets. Using version 1.15.7 of Traveller's gear. No other equipment was present, either in baubles or armor. This crash does not happen with the Seraph's Shoulders. Forge 1307.

**Comment by Alaberti** [comment]
On the plus side, the memory leak appears to be fixed.

**Comment by BluSunrize** [comment]
did the spaulders go into the slot? Can you load the world up again? Or does the crash persist?

**Comment by Alaberti** [comment]
The spaulders do not go into the slot, and I can load the world again. Seems like they disappear afterwards sometimes.

**Comment by BluSunrize** [comment]
That is very odd. The only suggestion I have is storing all your inventory safely and resetting your player file or trying to modify your NBT data with an NBT editor. I have never had to deal with this, or rather only in my dev environment, where I could adapt code on the fly to fix this.
It's on my To-Do for the next build, I will try to add a check so that attribute modifiers do not get applied twice.

Thanks for the report, I'll leave this issue open as a reminder ^^
