### ISSUE TITLE
Unable to load world/existing world with mod enabled.

### ISSUE THREAD

**Issue by plazia** [BluSunrize/WitchingGadgets#35]
Hi there, I can get your mod to load up with Minecraft but when I start a new world or indeed load an existing one I get this output http://pastebin.com/tGwDWVpT and I am booted back to the main menu.

Disable your mod and I can get through and start new worlds instantly.

**Comment by Alaberti** [comment]
Looking through that file, it looks like Minefactory reloaded is having a problem with Thaumcraft. Can you verify your versions of each, and are they the absolute latest versions?

**Comment by plazia** [comment]
I can give you the version numbers if you need them.

CoFHCore-[1.7.10]3.0.0RC7-211
CoFHLib-[1.7.10]1.0.0RC7-127
MineFactoryReloaded-[1.7.10]2.8.0RC8-86
RedstoneArsenal-[1.7.10]1.1.0RC7-65
ThermalDynamics-[1.7.10]1.0.0RC8-105
ThermalExpansion-[1.7.10]4.0.0RC7-141
ThermalFoundation-[1.7.10]1.0.0RC7-62
THAUMCRAFT-1.7.10-4.2.3.5

I think these are close to the latest. I've even updated them to try and resolve this issue but to no avail.
I hope this information helps.

**Comment by Alaberti** [comment]
How many mods are you running? I see this: Caused by: java.lang.StackOverflowError and that suggests to me you may not have enough memory allocated to add another mod. It looks like may have run out of memory while calling recipes, but I'm no expert. 

You might want to see if bumping up the memory/removing a few mods after you've added this one helps; if it doesn't, report this issue to @Azanor and @skyboy and see what they think.

**Comment by BluSunrize** [comment]
Why does no one ever read the FAQ or past issues. Disabled nugget transmutation in the config.

**Comment by plazia** [comment]
BluSunrize - please forgive me. You're absolutely right I think in fact it was you who informed me before about this issue and nugget transmutation resolved the issue. I think since subsequent updates or re-installation of instances of Resonant Rise through the AT-Launcher the config was re-written. My apologies and thanks for the response.
